/*!
 * Modernizr v2.6.2
 * www.modernizr.com
 *
 * Copyright (c) Faruk Ates, Paul Irish, Alex Sexton
 * Available under the BSD and MIT licenses: www.modernizr.com/license/
 */

/*
 * Modernizr tests which native CSS3 and HTML5 features are available in
 * the current UA and makes the results available to you in two ways:
 * as properties on a global Modernizr object, and as classes on the
 * <html> element. This information allows you to progressively enhance
 * your pages with a granular level of control over the experience.
 *
 * Modernizr has an optional (not included) conditional resource loader
 * called Modernizr.load(), based on Yepnope.js (yepnopejs.com).
 * To get a build that includes Modernizr.load(), as well as choosing
 * which tests to include, go to www.modernizr.com/download/
 *
 * Authors        Faruk Ates, Paul Irish, Alex Sexton
 * Contributors   Ryan Seddon, Ben Alman
 */

window.Modernizr=function(l,h,w){function t(a,b){return typeof a===b}function M(a,b){for(var c in a){var e=a[c];if(!~(""+e).indexOf("-")&&o[e]!==w)return b=="pfx"?e:true}return false}function m(a,b,c){var e=a.charAt(0).toUpperCase()+a.slice(1),k=(a+" "+N.join(e+" ")+e).split(" ");if(t(b,"string")||t(b,"undefined"))return M(k,b);else{k=(a+" "+O.join(e+" ")+e).split(" ");a:{a=k;for(var p in a){e=b[a[p]];if(e!==w){if(c===false){b=a[p];break a}if(t(e,"function")){b=e.bind(c||b);break a}b=e;break a}}b=
false}return b}}function V(){j.input=function(a){for(var b=0,c=a.length;b<c;b++)A[a[b]]=!!(a[b]in n);if(A.list)A.list=!!(h.createElement("datalist")&&l.HTMLDataListElement);return A}("autocomplete autofocus list placeholder max min multiple pattern required step".split(" "));j.inputtypes=function(a){for(var b=0,c,e,k=a.length;b<k;b++){n.setAttribute("type",e=a[b]);if(c=n.type!=="text"){n.value=E;n.style.cssText="position:absolute;visibility:hidden;";if(/^range$/.test(e)&&n.style.WebkitAppearance!==
w){q.appendChild(n);c=h.defaultView;c=c.getComputedStyle&&c.getComputedStyle(n,null).WebkitAppearance!=="textfield"&&n.offsetHeight!==0;q.removeChild(n)}else/^(search|tel)$/.test(e)||(c=/^(url|email)$/.test(e)?n.checkValidity&&n.checkValidity()===false:n.value!=E)}P[a[b]]=!!c}return P}("search tel url email datetime date month week time datetime-local number range color".split(" "))}var j={},q=h.documentElement,d=h.createElement("modernizr"),o=d.style,n=h.createElement("input"),E=":)",Q={}.toString,
B=" -webkit- -moz- -o- -ms- ".split(" "),N="Webkit Moz O ms".split(" "),O="Webkit Moz O ms".toLowerCase().split(" "),C={svg:"http://www.w3.org/2000/svg"};d={};var P={},A={},F=[],G=F.slice,D,x=function(a,b,c,e){var k,p,r=h.createElement("div"),v=h.body,u=v||h.createElement("body");if(parseInt(c,10))for(;c--;){k=h.createElement("div");k.id=e?e[c]:"modernizr"+(c+1);r.appendChild(k)}c=['&#173;<style id="smodernizr">',a,"</style>"].join("");r.id="modernizr";(v?r:u).innerHTML+=c;u.appendChild(r);if(!v){u.style.background=
"";u.style.overflow="hidden";p=q.style.overflow;q.style.overflow="hidden";q.appendChild(u)}a=b(r,a);if(v)r.parentNode.removeChild(r);else{u.parentNode.removeChild(u);q.style.overflow=p}return!!a},R=function(){var a={select:"input",change:"input",submit:"form",reset:"form",error:"img",load:"img",abort:"img"};return function(b,c){c=c||h.createElement(a[b]||"div");b="on"+b;var e=b in c;if(!e){c.setAttribute||(c=h.createElement("div"));if(c.setAttribute&&c.removeAttribute){c.setAttribute(b,"");e=t(c[b],
"function");t(c[b],"undefined")||(c[b]=w);c.removeAttribute(b)}}return e}}(),H={}.hasOwnProperty,I;I=!t(H,"undefined")&&!t(H.call,"undefined")?function(a,b){return H.call(a,b)}:function(a,b){return b in a&&t(a.constructor.prototype[b],"undefined")};if(!Function.prototype.bind)Function.prototype.bind=function(a){var b=this;if(typeof b!="function")throw new TypeError;var c=G.call(arguments,1),e=function(){if(this instanceof e){var k=function(){};k.prototype=b.prototype;k=new k;var p=b.apply(k,c.concat(G.call(arguments)));
if(Object(p)===p)return p;return k}else return b.apply(a,c.concat(G.call(arguments)))};return e};d.flexbox=function(){return m("flexWrap")};d.flexboxlegacy=function(){return m("boxDirection")};d.canvas=function(){var a=h.createElement("canvas");return!!(a.getContext&&a.getContext("2d"))};d.canvastext=function(){return!!(j.canvas&&t(h.createElement("canvas").getContext("2d").fillText,"function"))};d.webgl=function(){return!!l.WebGLRenderingContext};d.touch=function(){var a;if("ontouchstart"in l||l.DocumentTouch&&
h instanceof DocumentTouch)a=true;else x(["@media (",B.join("touch-enabled),("),"modernizr){#modernizr{top:9px;position:absolute}}"].join(""),function(b){a=b.offsetTop===9});return a};d.geolocation=function(){return"geolocation"in navigator};d.postmessage=function(){return!!l.postMessage};d.websqldatabase=function(){return!!l.openDatabase};d.indexedDB=function(){return!!m("indexedDB",l)};d.hashchange=function(){return R("hashchange",l)&&(h.documentMode===w||h.documentMode>7)};d.history=function(){return!!(l.history&&
history.pushState)};d.draganddrop=function(){var a=h.createElement("div");return"draggable"in a||"ondragstart"in a&&"ondrop"in a};d.websockets=function(){return"WebSocket"in l||"MozWebSocket"in l};d.rgba=function(){o.cssText="background-color:rgba(150,255,150,.5)";return!!~(""+o.backgroundColor).indexOf("rgba")};d.hsla=function(){o.cssText="background-color:hsla(120,40%,100%,.5)";return!!~(""+o.backgroundColor).indexOf("rgba")||!!~(""+o.backgroundColor).indexOf("hsla")};d.multiplebgs=function(){o.cssText=
"background:url(https://),url(https://),red url(https://)";return/(url\s*\(.*?){3}/.test(o.background)};d.backgroundsize=function(){return m("backgroundSize")};d.borderimage=function(){return m("borderImage")};d.borderradius=function(){return m("borderRadius")};d.boxshadow=function(){return m("boxShadow")};d.textshadow=function(){return h.createElement("div").style.textShadow===""};d.opacity=function(){var a=B.join("opacity:.55;")+"";o.cssText=a;return/^0.55$/.test(o.opacity)};d.cssanimations=function(){return m("animationName")};
d.csscolumns=function(){return m("columnCount")};d.cssgradients=function(){var a=("background-image:"+"-webkit- ".split(" ").join("gradient(linear,left top,right bottom,from(#9f9),to(white));background-image:")+B.join("linear-gradient(left top,#9f9, white);background-image:")).slice(0,-17);o.cssText=a;return!!~(""+o.backgroundImage).indexOf("gradient")};d.cssreflections=function(){return m("boxReflect")};d.csstransforms=function(){return!!m("transform")};d.csstransforms3d=function(){var a=!!m("perspective");
a&&"webkitPerspective"in q.style&&x("@media (transform-3d),(-webkit-transform-3d){#modernizr{left:9px;position:absolute;height:3px;}}",function(b){a=b.offsetLeft===9&&b.offsetHeight===3});return a};d.csstransitions=function(){return m("transition")};d.fontface=function(){var a;x('@font-face {font-family:"font";src:url("https://")}',function(b,c){var e=h.getElementById("smodernizr");e=(e=e.sheet||e.styleSheet)?e.cssRules&&e.cssRules[0]?e.cssRules[0].cssText:e.cssText||"":"";a=/src/i.test(e)&&e.indexOf(c.split(" ")[0])===
0});return a};d.generatedcontent=function(){var a;x(['#modernizr{font:0/0 a}#modernizr:after{content:"',E,'";visibility:hidden;font:3px/1 a}'].join(""),function(b){a=b.offsetHeight>=3});return a};d.video=function(){var a=h.createElement("video"),b=false;try{if(b=!!a.canPlayType){b=new Boolean(b);b.ogg=a.canPlayType('video/ogg; codecs="theora"').replace(/^no$/,"");b.h264=a.canPlayType('video/mp4; codecs="avc1.42E01E"').replace(/^no$/,"");b.webm=a.canPlayType('video/webm; codecs="vp8, vorbis"').replace(/^no$/,
"")}}catch(c){}return b};d.audio=function(){var a=h.createElement("audio"),b=false;try{if(b=!!a.canPlayType){b=new Boolean(b);b.ogg=a.canPlayType('audio/ogg; codecs="vorbis"').replace(/^no$/,"");b.mp3=a.canPlayType("audio/mpeg;").replace(/^no$/,"");b.wav=a.canPlayType('audio/wav; codecs="1"').replace(/^no$/,"");b.m4a=(a.canPlayType("audio/x-m4a;")||a.canPlayType("audio/aac;")).replace(/^no$/,"")}}catch(c){}return b};d.localstorage=function(){try{localStorage.setItem("modernizr","modernizr");localStorage.removeItem("modernizr");
return true}catch(a){return false}};d.sessionstorage=function(){try{sessionStorage.setItem("modernizr","modernizr");sessionStorage.removeItem("modernizr");return true}catch(a){return false}};d.webworkers=function(){return!!l.Worker};d.applicationcache=function(){return!!l.applicationCache};d.svg=function(){return!!h.createElementNS&&!!h.createElementNS(C.svg,"svg").createSVGRect};d.inlinesvg=function(){var a=h.createElement("div");a.innerHTML="<svg/>";return(a.firstChild&&a.firstChild.namespaceURI)==
C.svg};d.smil=function(){return!!h.createElementNS&&/SVGAnimate/.test(Q.call(h.createElementNS(C.svg,"animate")))};d.svgclippaths=function(){return!!h.createElementNS&&/SVGClipPath/.test(Q.call(h.createElementNS(C.svg,"clipPath")))};for(var J in d)if(I(d,J)){D=J.toLowerCase();j[D]=d[J]();F.push((j[D]?"":"no-")+D)}j.input||V();j.addTest=function(a,b){if(typeof a=="object")for(var c in a)I(a,c)&&j.addTest(c,a[c]);else{a=a.toLowerCase();if(j[a]!==w)return j;b=typeof b=="function"?b():b;q.className+=
" "+(b?"":"no-")+a;j[a]=b}return j};o.cssText="";d=n=null;(function(a,b){function c(){var f=z.elements;return typeof f=="string"?f.split(" "):f}function e(f){var g=S[f[T]];if(!g){g={};K++;f[T]=K;S[K]=g}return g}function k(f,g,i){g||(g=b);if(y)return g.createElement(f);i||(i=e(g));g=i.cache[f]?i.cache[f].cloneNode():W.test(f)?(i.cache[f]=i.createElem(f)).cloneNode():i.createElem(f);return g.canHaveChildren&&!u.test(f)?i.frag.appendChild(g):g}function p(f,g){if(!g.cache){g.cache={};g.createElem=f.createElement;
g.createFrag=f.createDocumentFragment;g.frag=g.createFrag()}f.createElement=function(i){if(!z.shivMethods)return g.createElem(i);return k(i,f,g)};f.createDocumentFragment=Function("h,f","return function(){var n=f.cloneNode(),c=n.createElement;h.shivMethods&&("+c().join().replace(/\w+/g,function(i){g.createElem(i);g.frag.createElement(i);return'c("'+i+'")'})+");return n}")(z,g.frag)}function r(f){f||(f=b);var g=e(f);if(z.shivCSS&&!L&&!g.hasCSS){var i,s=f;i=s.createElement("p");s=s.getElementsByTagName("head")[0]||
s.documentElement;i.innerHTML="x<style>article,aside,figcaption,figure,footer,header,hgroup,nav,section{display:block}mark{background:#FF0;color:#000}</style>";i=s.insertBefore(i.lastChild,s.firstChild);g.hasCSS=!!i}y||p(f,g);return f}var v=a.html5||{},u=/^<|^(?:button|map|select|textarea|object|iframe|option|optgroup)$/i,W=/^(?:a|b|code|div|fieldset|h1|h2|h3|h4|h5|h6|i|label|li|ol|p|q|span|strong|style|table|tbody|td|th|tr|ul)$/i,L,T="_html5shiv",K=0,S={},y;(function(){try{var f=b.createElement("a");
f.innerHTML="<xyz></xyz>";L="hidden"in f;y=f.childNodes.length==1||function(){b.createElement("a");var i=b.createDocumentFragment();return typeof i.cloneNode=="undefined"||typeof i.createDocumentFragment=="undefined"||typeof i.createElement=="undefined"}()}catch(g){y=L=true}})();var z={elements:v.elements||"abbr article aside audio bdi canvas data datalist details figcaption figure footer header hgroup mark meter nav output progress section summary time video",shivCSS:v.shivCSS!==false,supportsUnknownElements:y,
shivMethods:v.shivMethods!==false,type:"default",shivDocument:r,createElement:k,createDocumentFragment:function(f,g){f||(f=b);if(y)return f.createDocumentFragment();g=g||e(f);for(var i=g.frag.cloneNode(),s=0,U=c(),X=U.length;s<X;s++)i.createElement(U[s]);return i}};a.html5=z;r(b)})(this,h);j._version="2.6.2";j._prefixes=B;j._domPrefixes=O;j._cssomPrefixes=N;j.mq=function(a){var b=l.matchMedia||l.msMatchMedia;if(b)return b(a).matches;var c;x("@media "+a+" { #modernizr { position: absolute; } }",function(e){c=
(l.getComputedStyle?getComputedStyle(e,null):e.currentStyle).position=="absolute"});return c};j.hasEvent=R;j.testProp=function(a){return M([a])};j.testAllProps=m;j.testStyles=x;j.prefixed=function(a,b,c){return b?m(a,b,c):m(a,"pfx")};q.className=q.className.replace(/(^|\s)no-js(\s|$)/,"$1$2")+(" js "+F.join(" "));return j}(this,this.document);

